let A=70;
A++
console.log(A)
let A=60;
A+
var.log(A)
A++
console.log(A)
const C=150
let number1=1635
let number2=564
let result=number1+number2
console.log(result)
let number20=2024
let syear=2023
let Jyear=2025
let result=number20+syear+Jyear;
console.log(result)


function palindrom(str){
    let reversedString=str.tolowercase().split('').reverse().join('')
    if(str===reversedString){
        console.log(`${str} is a palidrom`)
    }
    return reversedString
}
console.log(palindrom('dad'));
console.log(palindrom('MUM'));
console.log(palindrom('cat'));
